改用webhook url和把consstant.json移到/
HiZollo/Junior-HiZollo pull request #28
Opened 2022-11-23 02:44 UTC by cutebear0123

改用webhook url和把constant.json移到`/`
原因：
webhook url可以直接copy比較方便
constant.json算是config所以移到`/`

~~這名稱夠正式了吧~~
~~不行的話只能請AC取名大師了~~

2022-11-23 04:58 UTC, kyometori requested changes
我不知道 @Zollo757347 的想法是什麼，但我是沒什麼意見，只是下面這些的命名我覺得要改一下：
1. env 鍵名要加 URL，不然誰知道是 Webhook 的什麼
2. Error 的內容沒有改到
3. 在根目錄的東西用 @root 存取比較好
4. 這樣的話 `registerWebhook` 腳本應該要提供 Webhook URL，現在版本只有 token 和 id
5. 請告訴我們你有沒有編譯和測試過你的更改

這些建議因為太多地方了我只挑一個地方出來，其它的就同理

2022-11-23 04:58 UTC, kyometori commented on config.ts
> +if (!process.env.MAIN_WEBHOOK) throw new Error('Main webhook token not configured.');
```suggestion
if (!process.env.MAIN_WEBHOOK_URL) throw new Error('Main webhook url not configured.');
```

2022-11-23 04:58 UTC, kyometori commented on src/buttons/bugResponse.ts
> +import { mainGuild } from "../../constant.json";
```suggestion
import { mainGuild } from "@root/constant.json";
```

2022-11-23 04:59 UTC, kyometori commented
@Zollo757347 的意見就等他出來吧

2022-11-23 05:48 UTC, cutebear0123 commented on src/buttons/bugResponse.ts
> +import { mainGuild } from "../../constant.json";
謝謝大佬，我都不知道js可以這樣用

2022-11-23 05:50 UTC, cutebear0123 commented
我有編譯+測試過沒問題

2022-11-23 06:09 UTC, kyometori commented on src/buttons/bugResponse.ts
> +import { mainGuild } from "../../constant.json";
那是我們有設定路徑別名，一般是不能這樣的

2022-11-23 06:11 UTC, kyometori commented
還有 register webhook 腳本的部分，改完之後再按叫我 review

2022-11-23 06:27 UTC, cutebear0123 commented
好惹
可以按review了

2022-11-23 06:57 UTC, kyometori commented
我講錯了 是按 review 叫我（
隨便 這次我自己按

2022-11-23 07:04 UTC, kyometori requested changes
README 中的 Webhook 範例也要改成新的

2022-11-23 07:27 UTC, Zollo757347 approved these changes
我這邊沒什麼問題，再來只要把 @kyometori 丟出來的 request 改一改就好。

2022-11-23 15:31 UTC, kyometori commented
你只有改 env 的格式，沒有改 webhook 註冊 script 的使用範例

2022-11-23 19:26 UTC, cutebear0123 commented
好了

2022-11-24 03:37 UTC, kyometori approved these changes
好，我這邊看起來也覺得可以了

2022-11-24 03:37 UTC, merged