Adding more tweaks and functionality
HiZollo/Junior-HiZollo pull request #32
Opened 2022-11-30 15:16 UTC by Mantou1233

# features
- you can log say command’s record now from guild, by creating a text channel called `hz-message-log`
- get msg can support count of messages to get, limiting from 1 to 100 message. (optional, defaults to 100)

# fixes
- config.ts now automatically get bot id from base64 decrypting the first sector of the token.

all code is checked and ran by tsc and tested.
i’ll revert constants tomorrow, please review the PR for now

2022-11-30 15:33 UTC, kyometori requested changes
1. 請把 `config.ts` 和 `constant.json` 中你的測試用的設定改回原本 HiZollo 的設定
2. 你把 `YoutubeUtil`改名為了 `MusicUtil`，但好像沒有改掉其它地方，也許目前把他改回來是比較好的。
3. `Say.ts` 中，如果你都把 content 放在 \`\`\` 之中了，那應該就不用 `removeMd` 了吧，那只會讓 content 多一堆不知道哪裡來的 `\`。
  - 我是覺得不用額外抱一層 \`\`\`，直接放 content 就好了，應該沒什麼差吧。

應該還有些我沒提到的，等上面這些改完或有共識之後，我們再繼續往下。

2022-12-01 06:24 UTC, kyometori commented
我剛剛才看到你有說你明天再把 constant 改回來，不過目前一樣就是這樣還有我說的那些

2022-12-01 10:15 UTC, Mantou1233 commented
fixed the above issue, probably can merge rn, lets wait 4 zollo

2022-12-01 10:54 UTC, kyometori commented
u have to request me review again

2022-12-01 11:00 UTC, kyometori requested changes
目前看到的問題有這些。

2022-12-01 11:16 UTC, kyometori commented
大致上沒有問題了，但我還有最後一個問題：你有用 Forum Channel 做實驗嗎？

因為是新的東西，而且有看到 Forum Channel 是有實作 TextBasedChannel 做實驗，所以我不知道 Forum Channel 會不會過 `isTextBased()`。

如果會的話，57 行那要改一下，不會就不會。

這個問題解決完後，我這邊的 review 就完成了。

2022-12-01 11:19 UTC, Mantou1233 commented
forum 應該是不過 `isTextBased()`的。
`logChannel` 過去if之後的type是 `NewsChannel | TextChannel`

2022-12-01 11:31 UTC, kyometori commented
好，我剛剛讀了一下 djs 原碼得到的也是差不多的結論，這樣的話我這邊目前沒問題了。

2022-12-01 11:41 UTC, kyometori approved these changes
好了，我這邊看可以了。

2022-12-02 05:48 UTC, merged