total improvement on /z aliases
HiZollo/Junior-HiZollo pull request #44
Opened 2023-04-24 11:34 UTC by Mantou1233

fixed that you cannot use /z for autocorrect and error when deploying subcommands with no related z command name. (it will ignore it.)

2023-04-24 14:20 UTC, Zollo757347 commented on src/classes/AutocompleteManager.ts
> +      // 因爲z指令都是subcommands，所以getSubCommand是required
```suggestion
    if (commandName === "z") {
      // 因爲 z 指令都是 subcommands，所以 getSubCommand 是 required
```

2023-04-24 14:20 UTC, Zollo757347 commented on src/classes/AutocompleteManager.ts
> +    }
```suggestion
    else if (interaction.options.getSubcommand(false)) {
      commandName += '_' + interaction.options.getSubcommand(false);
    }
```

2023-04-24 14:21 UTC, Zollo757347 commented on src/deploy.ts
> +      command.setName(shortcut);
```suggestion
      const shortcut = Translator.getZShortcut([parent, command.name]);
      if (!shortcut) return;
      command.setName(shortcut);
```

2023-04-24 14:37 UTC, Zollo757347 approved these changes

2023-04-24 16:41 UTC, kyometori requested changes
我想註解風格也要規範一下

2023-04-24 16:41 UTC, kyometori commented on src/classes/AutocompleteManager.ts
> +      // 因爲z指令都是subcommands，所以getSubCommand是required
```suggestion
      // 因為 z 指令都是群組指令，所以 getSubcommand 是 required
```

2023-04-24 16:42 UTC, kyometori commented
笑死 @Zollo757347 好像有 request 過，但被忽略了

2023-04-25 05:53 UTC, kyometori approved these changes

2023-04-25 05:53 UTC, merged