feature:sticker support for hz-network
HiZollo/Junior-HiZollo pull request #59
Opened 2023-12-22 19:32 UTC by cutebear0123

Added sticker support for hz-network

2023-12-22 19:50 UTC, kyometori requested changes

2023-12-22 19:50 UTC, kyometori commented on src/classes/HZNetwork.ts
> +    )
```suggestion
})
```

2023-12-22 19:50 UTC, kyometori commented on src/classes/HZNetwork.ts
> +        name: s.url.split('/')[s.url.split('/').length - 1]
`s.url.split('/')` 被呼叫了兩次，應該在開頭先把結果存起來比較好吧

2023-12-24 12:18 UTC, kyometori approved these changes

2023-12-27 11:58 UTC, kyometori requested changes
1. 你後面的 commit 把你前面被我 request changes 的東西又蓋回去了
2. 你可以解釋一下你寫的 code 大致上的行為嗎（做了什麼、演算法），還有我有以下的疑慮：
  1. 回覆的 fetch message 會不會導致 api spam
  2. 我看到他是找前 20 則，那如果回覆的訊息太過前面（e.g. 250 則），會發生什麼事？

2023-12-27 11:58 UTC, kyometori commented on src/classes/HZNetwork.ts
> +    )
```suggestion
  })
```

2023-12-27 11:58 UTC, kyometori commented on src/classes/HZNetwork.ts
> +        name: s.url.split('/')[s.url.split('/').length - 1]
同之前。

2023-12-27 20:10 UTC, cutebear0123 commented
> 1. 你後面的 commit 把你前面被我 request changes 的東西又蓋回去了
> 2. 你可以解釋一下你寫的 code 大致上的行為嗎（做了什麼、演算法），還有我有以下的疑慮：
>   1. 回覆的 fetch message 會不會導致 api spam
>   2. 我看到他是找前 20 則，那如果回覆的訊息太過前面（e.g. 250 則），會發生什麼事？

1.fixed
2.每次reply去每個頻道fetch前20個訊息
如果有同樣內容和發送人就放連結
然後發送的時候為了避免重複訊息，如果有重複會在後面加上u+200b
2.1.我測試66不會
2.2.沒有連結

2023-12-30 02:16 UTC, kyometori commented
code 我目前看是沒什麼問題。不過我好奇為什麼改成使用 embed 顯示回覆，而不是使用舊版回覆的格式，這樣有什麼優點嗎。

另外如果 fetch 的各頻道中回覆的 message，有沒有辦法直接使用 reply？

然後 @Zollo757347 你要看看嗎

2023-12-30 02:28 UTC, cutebear0123 commented
> code 我目前看是沒什麼問題。不過我好奇為什麼改成使用 embed 顯示回覆，而不是使用舊版回覆的格式，這樣有什麼優點嗎。
> 
> 另外如果 fetch 的各頻道中回覆的 message，有沒有辦法直接使用 reply？
> 
> 然後 @Zollo757347 你要看看嗎

1.embed有頭貼
2.webhook沒有reply

2023-12-30 02:59 UTC, kyometori approved these changes
剩下該問的都在 Discord 上問完了，從以下訊息開始：
https://discord.com/channels/572733182412193792/572733182412193794/1190480650587885578

2023-12-30 05:39 UTC, Zollo757347 approved these changes

2023-12-30 05:39 UTC, merged