some fixes
HiZollo/Junior-HiZollo pull request #60
Opened 2024-01-06 01:07 UTC by cutebear0123

Add soon because I don't have input method

2024-01-20 16:00 UTC, kyometori commented
ban words 我覺得允許放 regex 比較好，把裡面的字串轉成 regex 然後檢查，類似 `banwords.map(s => new RegExp(s)).some(r => r.test(content))` 之類的，看怎麼寫比較好。這樣就可以放回之前那個 regex 了（除非他有什麼問題）。

2024-01-20 16:06 UTC, kyometori requested changes
你這個 reformat 真的超煩
<img width="607" alt="DontReformatCodeInFeaturePR" src="https://github.com/HiZollo/Junior-HiZollo/assets/73421607/b3d16144-358d-4269-b456-f3d881df3965">

2024-01-20 16:06 UTC, kyometori commented on src/classes/WebhookLogger.ts
> +  public networkUnallowPost(portNo: string, guild: Guild, author: User, message: Message): void {
傳 content 進來就好了，不用傳整個 message

2024-01-20 16:06 UTC, kyometori commented on src/classes/WebhookLogger.ts
> +  訊息內容：${message.content}
一般而言我們 network 不會 log 使用者的 content 在後台，或是如果你認為被禁止的內容要 log 出來比較好好像也不是不行就是了。

2024-01-20 16:06 UTC, kyometori commented on src/classes/HZNetwork.ts
> +    return this.bannedWords.some(word => content.includes(word));
如同我留言講的把字串檢查改成 regex 檢查

2024-01-22 14:47 UTC, Zollo757347 commented
建議把 `checkMessageSafe` 改名成 `checkMessageBanned` 或 `isBannedMessage`，現在函式名稱和他實際做的事是相反的。另外這個函式理論上不應該被外面存取，所以改成 private 會比較好。

2024-01-22 17:07 UTC, kyometori commented
我投 `isBannedMessage` 一票

2024-01-22 17:22 UTC, cutebear0123 commented
我回家改 (aka soon :tm:

2024-01-26 15:49 UTC, kyometori approved these changes

2024-01-29 01:13 UTC, Zollo757347 approved these changes

2024-01-29 01:13 UTC, merged