feature: add weighted choose command & fix
HiZollo/Junior-HiZollo pull request #61
Opened 2024-06-29 18:20 UTC by Mantou1233

added weighted choose command
```
z!choose 5:@pen_qun 10000:@zollus
z!choose 0.1:stupid 3:smart
z!choose 2:奶茶 咖啡 可樂
```
現在他可以用來抽獎了！（

還有兩個小修復（？
- ts的小問題
- StackOverflow沒有錯誤信息

沒了 想到再加

2024-06-29 18:20 UTC, Mantou1233 commented
pushed

2024-07-01 05:08 UTC, kyometori commented
你的 code 跑不過 checks。
我稍微看了一下，你可能要升級一下 HiZollo 本體的 Calculator？因為他目前還在舊版，沒有 StackOverflow 的 錯誤。

2024-07-01 05:49 UTC, kyometori requested changes
`.github/workflow` 裡面 node 版本的也要改，不然 checks 還是跑不過

2024-07-01 05:49 UTC, kyometori commented on src/commands/Calc.ts
> +    [ErrorCodes.StackOverflow]: `超出堆疊上限`,
```suggestion
    [ErrorCodes.StackOverflow]: `你的運算式太長了，請你考慮分段計算，不然我的腦袋要爆了。`, 
```

2024-07-01 05:58 UTC, kyometori requested changes
你沒有上傳更改後的 lockfile。

另外，請你也把 typescript 的版本 bump 到最新。

2024-07-02 17:55 UTC, kyometori commented
#57 合併了，我猜應該是沒有衝突，但還是拉一下，因為你有動東西的版本，檢查一下他寫的東西在你這個版本編譯會不會過可能比較好。

2024-07-05 16:12 UTC, Mantou1233 commented
k

2024-07-15 02:07 UTC, Mantou1233 commented
typescript updating had issues on djs
![image](https://github.com/user-attachments/assets/ba97c8a9-d774-4c95-a79c-046a11bd54de)
i will not update the version of anything then

2024-07-17 02:32 UTC, Mantou1233 commented
i dunno why is it failing even if i downgraded node versions or typescript versions

2024-08-26 12:00 UTC, kyometori commented
#62 解決了所有版本和 type 的問題，你可以 revert 掉更新版本的 commits，然後把 dev 拉回去。接著應該就能合併了。

2024-08-26 12:03 UTC, kyometori commented
看起來應該是回到 [21f9c70](https://github.com/HiZollo/Junior-HiZollo/pull/61/commits/21f9c70d86839ee47f590e1f32a65709e09339fd)

2024-08-28 21:43 UTC, Mantou1233 commented
@kyometori finished

2024-08-29 05:28 UTC, kyometori requested changes
```
Error: src/commands/Calc.ts(91,5): error TS1117: An object literal cannot have multiple properties with the same name.
Error: Process completed with exit code 1.
```
Calc 有問題要修掉（不要直接 apply suggestion，上面還有一行註解）。還有另一個問題，剩下看起來很好。

2024-08-29 05:28 UTC, kyometori commented on src/commands/Calc.ts
> +    [ErrorCodes.StackOverflow]: `超出堆疊上限`,
```suggestion
```

2024-08-30 09:56 UTC, kyometori approved these changes

2024-08-30 10:21 UTC, merged