一些雜事
HiZollo/Junior-HiZollo pull request #63
Opened 2024-08-28 04:04 UTC by Zollo757347

- 新增與修改
  - `server` 指令現在會顯示更詳細的頻道資料
  - `vote` 指令現在使用時會跳出即將下架的提示，下一個版本將會正式下架
  - 新增一些隱藏指令的回應
  - 把隱藏指令的回應機率改回過去的狀態
  - 刪除一些會被 `wronghelp` 判定為 `help` 的條件
- 修復漏洞
  - `buttonrole` 指令遇到 Unicode 表情時會出問題
  - `gomoku` 指令的英文字母在某些手機裝置會被合併成國旗

2024-08-28 17:02 UTC, kyometori requested changes

2024-08-28 17:02 UTC, kyometori commented on src/classes/HiddenCommand.ts
> +    const response = Math.random() < 0.002 ? randomElement(epic) : randomElement(notEpic);
all time response 應該是 2%
```suggestion
const response = Math.random() < 0.02 ? randomElement(epic) : randomElement(notEpic);
```

2024-08-28 21:57 UTC, Mantou1233 commented on src/classes/HiddenCommand.ts
> +    (/[\x21-\x7e]/.test(location[0]) ? " " : "") + location +
would it be better if we seperated the regexp to a constant?
also could we use this function on other places?

2024-08-28 22:20 UTC, Mantou1233 reviewed
不知道爲什麽review了一下，請看看

2024-08-28 22:20 UTC, Mantou1233 commented on src/commands/Buttonrole.ts
> +    const custom = emojiResolvable?.match(/<?(a)?:?(\w{2,32}):(\d{17,20})>?/)?.[3] ?? null;
use emojiRegex()?

2024-08-28 22:20 UTC, Mantou1233 commented on src/classes/HiddenCommand.ts
> +    (/[\x21-\x7e]/.test(location[0]) ? " " : "") + location +
將這個regex分成一個constant（ascii?
因爲其實有點不可讀 我想了一下才get到

2024-08-28 22:20 UTC, Mantou1233 commented on src/commands/Server.ts
> +          console.log(name);
remove console log

2024-08-28 22:20 UTC, Mantou1233 commented on src/commands/Vote.ts
> +      .setDescription("這個指令將在下個更新中下架，建議你使用 Discord 內建的[投票功能](https://support.discord.com/hc/zh-tw/articles/22163184112407-%E6%8A%95%E7%A5%A8%E5%B8%B8%E8%A6%8B%E5%95%8F%E9%A1%8C)。")
`建議` -> `推薦`?

2024-08-29 01:11 UTC, Zollo757347 commented on src/commands/Buttonrole.ts
> +    const custom = emojiResolvable?.match(/<?(a)?:?(\w{2,32}):(\d{17,20})>?/)?.[3] ?? null;
有點不太理解為什麼要再用一次 `emogiRegex`，參數在執行 `execute` 之前就已經檢查過型別了，所以確定它一定會是合法的表情符號（或 null），不需要再檢查一次。

2024-08-29 01:13 UTC, Mantou1233 commented on src/commands/Buttonrole.ts
> +    const custom = emojiResolvable?.match(/<?(a)?:?(\w{2,32}):(\d{17,20})>?/)?.[3] ?? null;
因為這裡有用到emoji的regexp啊？不然用那個庫幹嘛（

2024-08-29 01:42 UTC, Zollo757347 commented on src/commands/Buttonrole.ts
> +    const custom = emojiResolvable?.match(/<?(a)?:?(\w{2,32}):(\d{17,20})>?/)?.[3] ?? null;
那個套件是檢查字串是不是 Unicode 表情的，這邊是要檢查表情的名稱，所以那個套件用不到。

2024-08-29 05:34 UTC, kyometori commented on src/commands/Buttonrole.ts
> +    const custom = emojiResolvable?.match(/<?(a)?:?(\w{2,32}):(\d{17,20})>?/)?.[3] ?? null;
這邊確實沒有問題，也不用使用 emoji-regex，我直接 resolve 了

2024-08-29 05:35 UTC, kyometori approved these changes

2024-08-29 08:04 UTC, merged